language: node_js

dist: trusty

node_js:
 - "0.12.0"
 - "4.1.1"
 - "5.1.0"
 - "6.4.0"
 - "7.8.0"

install:
 - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
 - echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get update
 - sudo apt-get install mono-devel
 - npm install -g grunt-cli
 - npm install

script:
 - gcc -v
 - mono -V
 - npm test