language: node_js

dist: trusty

node_js:
 - "0.12.0"
 - "4.1.1"
 - "5.1.0"
 - "6.4.0"
 - "7.8.0"

install:
 - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
 - echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
 - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
 - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
 - sudo apt-get update
 - sudo apt-get install mono-devel
 - npm install

script:
 - npm test
 - sudo apt-get autoremove mono-devel -y
 - sudo apt-get install dotnet-dev-1.0.1
 - npm install
 - EDGE_USE_CORECLR=1 node tools/test.js
